server:
  port: 8099 # 修改Tomcat端口号
spring:
  datasource:
    # 数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接地址, useSSL=false表示禁用SSL 改用用户名和密码认证, serverTimezone时区
    url: jdbc:mysql://localhost:3306/clouddrive?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    # 数据库用户名
    username: root
    # 数据库密码
    password: 123456
