spring:
  application:
    name: fileupdown-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddrive?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: wyqc
