spring:
  application:
    name: fileupdown-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddrive?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: wyqc
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 2000
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml

    # Hadoop HDFS configuration
hadoop:
  namenode:
    host: localhost
    port: 9000
  fs:
    defaultFS: hdfs://localhost:9000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 8090
mybatis:
  mapper-locations: classpath:mapper/*.xml

