version: '3.8'

services:
  frontend:
    build:
      context: ../apps/frontend
      dockerfile: ../../docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://backend:8080
    networks:
      - cloud-drive-network

  backend:
    build:
      context: ../apps/backend
      dockerfile: ../../docker/Dockerfile.backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cloud_drive
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root123
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - cloud-drive-network

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=cloud_drive
      - MYSQL_USER=cloud_drive
      - MYSQL_PASSWORD=cloud123
    volumes:
      - mysql_data:/var/lib/mysql
      - ../sql:/docker-entrypoint-initdb.d
    networks:
      - cloud-drive-network

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - cloud-drive-network

volumes:
  mysql_data:
    driver: local

networks:
  cloud-drive-network:
    driver: bridge