services:
  # Nacos service registry
  nacos:
    image: nacos/nacos-server:v2.2.0
    platform: linux/amd64
    container_name: nacos-server
    restart: unless-stopped
    ports:
      - "8848:8848"
      - "9848:9848"
    environment:
      - MODE=standalone
      - JVM_XMS=256m
      - JVM_XMX=256m
    volumes:
      - nacos_data:/home/nacos/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8848/nacos/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - cloud-drive-network

  # API Gateway
  gateway:
    build:
      context: ../apps/gateway
      dockerfile: ../../docker/Dockerfile.gateway
    platform: linux/amd64
    container_name: gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      nacos:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
    networks:
      - cloud-drive-network

  # Auth Service
  auth-service:
    build:
      context: ../apps/auth-service
      dockerfile: ../../docker/Dockerfile.auth-service
    platform: linux/amd64
    container_name: auth-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cloud_drive
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root123
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - cloud-drive-network

  # File Upload/Download Service
  fileupdown-service:
    build:
      context: ../apps/fileupdown-service
      dockerfile: ../../docker/Dockerfile.fileupdown-service
    platform: linux/amd64
    container_name: fileupdown-service
    restart: unless-stopped
    ports:
      - "8090:8090"
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cloud_drive
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root123
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - cloud-drive-network

  # Admin Service
  admin-service:
    build:
      context: ../apps/admin-service
      dockerfile: ../../docker/Dockerfile.admin-service
    platform: linux/amd64
    container_name: admin-service
    restart: unless-stopped
    ports:
      - "8083:8083"
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cloud_drive
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root123
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - cloud-drive-network

  # Membership Service
  membership-service:
    build:
      context: ../apps/membership-service
      dockerfile: ../../docker/Dockerfile.membership-service
    platform: linux/amd64
    container_name: membership-service
    restart: unless-stopped
    ports:
      - "8084:8084"
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cloud_drive
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root123
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - cloud-drive-network

  # File Management Service
  file-manage-service:
    build:
      context: ../apps/file-manage-service
      dockerfile: ../../docker/Dockerfile.file-manage-service
    platform: linux/amd64
    container_name: file-manage-service
    restart: unless-stopped
    ports:
      - "8099:8099"
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cloud_drive
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root123
    networks:
      - cloud-drive-network

  # File Recycle Service
  file-recycle-service:
    build:
      context: ../apps/file_recycle_server
      dockerfile: ../../docker/Dockerfile.file-recycle-service
    platform: linux/amd64
    container_name: file-recycle-service
    restart: unless-stopped
    ports:
      - "8086:8080"
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cloud_drive
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root123
    networks:
      - cloud-drive-network

  # Mail Service
  mail-service:
    build:
      context: ../apps/mail-service
      dockerfile: ../../docker/Dockerfile.mail-service
    platform: linux/amd64
    container_name: mail-service
    restart: unless-stopped
    ports:
      - "8087:8084"
    depends_on:
      nacos:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    networks:
      - cloud-drive-network

  # Frontend
  frontend:
    build:
      context: ../apps/frontend
      dockerfile: ../../docker/Dockerfile.frontend
    platform: linux/amd64
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - gateway
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://gateway:8080
    networks:
      - cloud-drive-network

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=cloud_drive
      - MYSQL_USER=cloud_drive
      - MYSQL_PASSWORD=cloud123
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ../sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s
    networks:
      - cloud-drive-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - cloud-drive-network

  # RabbitMQ Message Queue
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    platform: linux/amd64
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 30s
      timeout: 15s
      retries: 8
      start_period: 150s
    networks:
      - cloud-drive-network

  # Hadoop HDFS NameNode
  hadoop-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    platform: linux/amd64
    container_name: hadoop-namenode
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=clouddrive
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
    networks:
      - cloud-drive-network

  # Hadoop HDFS DataNode
  hadoop-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    platform: linux/amd64
    container_name: hadoop-datanode
    restart: always
    ports:
      - "9864:9864"
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
    depends_on:
      - hadoop-namenode
    networks:
      - cloud-drive-network

  # Flink JobManager
  flink-jobmanager:
    image: flink:1.15.2-scala_2.12
    container_name: flink-jobmanager
    ports:
      - "8085:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    networks:
      - cloud-drive-network

  # Flink TaskManager
  flink-taskmanager:
    image: flink:1.15.2-scala_2.12
    container_name: flink-taskmanager
    depends_on:
      - flink-jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    networks:
      - cloud-drive-network

volumes:
  mysql_data:
    driver: local
  nacos_data:
    driver: local
  hadoop_namenode:
    driver: local
  hadoop_datanode:
    driver: local

networks:
  cloud-drive-network:
    driver: bridge