services:
  # Frontend only
  frontend:
    build:
      context: ../apps/frontend
      dockerfile: ../../docker/Dockerfile.frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:8080
    networks:
      - cloud-drive-network

networks:
  cloud-drive-network:
    driver: bridge
