server:
  port: 8084

spring:
  application:
    name: membership-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: clouddrive

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    cn.sdu.clouddrive: DEBUG