server:
  port: 8084

spring:
  application:
    name: mail-service
  mail:
    # 发送者邮箱
    username: 2131611700@qq.com
    #申请到的授权码
    password: qwkjultpbmaahegi
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 端口号465或587
    port: 465
    protocol: smtps
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
          debug: true
          ssl: true

  # RabbitMQ配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 开启发送确认
    publisher-confirm-type: correlated
    # 开启发送失败退回
    publisher-returns: true
    # 开启消费者确认
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          multiplier: 2
          max-interval: 10000

  # Nacos服务发现配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  data:
    redis:
      host: localhost
      database: 2
      timeout: 10s
      port: 6379

# 自定义邮件配置
mail:
  verification:
    expire-minutes: 15  # 验证码过期时间（分钟）
    code-length: 6     # 验证码长度

# 日志配置
logging:
  level:
    cn.sdu.clouddrive.mailservice: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework.mail: DEBUG
