server:
  port: 8084

spring:
  application:
    name: mail-service

  # RabbitMQ配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 开启发送确认
    publisher-confirm-type: correlated
    # 开启发送失败退回
    publisher-returns: true
    # 开启手动确认模式
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          multiplier: 2

  # 邮件配置
  mail:
    host: smtp.qq.com
    port: 587
    username: your-email@qq.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.qq.com

  # Redis配置
  redis:
    host: localhost
    port: 6379
    database: 2  # 使用database 2专门存储邮件相关数据
    timeout: 10s
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0

  # Nacos服务发现配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

# 日志配置
logging:
  level:
    cn.sdu.clouddrive.mailservice: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework.mail: DEBUG

# 自定义配置
mail:
  retry:
    max-attempts: 3
    delay: 1000
  template:
    from: "clouddrive@example.com"
    system-name: "云盘系统"
