server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
                - PATCH
            allowedHeaders: "*"
            allow-credentials: true
            max-age: 3600
        add-to-simple-url-handler-mapping: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: resources-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**.jpg
          filters:
            - RewritePath=/api/user/(?<segment>.*),/$\{segment}.jpg
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**

        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/api/files/**
          filters:
            - StripPrefix=1
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=1
        - id: membership-service
          uri: lb://membership-service
          predicates:
            - Path=/api/membership/**
          filters:
            - StripPrefix=1
        - id: subscription-service
          uri: lb://membership-service
          predicates:
            - Path=/api/subscription/**
          filters:
            - StripPrefix=1
        - id: payment-service
          uri: lb://membership-service
          predicates:
            - Path=/api/payment/**
          filters:
            - StripPrefix=1
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*),/api/auth/$\{segment}

        - id: mail-service
          uri: lb://mail-service
          predicates:
            - Path=/api/mail/**



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    cn.sdu.clouddrive: DEBUG
    org.springframework.cloud.gateway: DEBUG