server:
  port: 8083

spring:
  application:
    name: admin-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: clouddrive

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    cn.sdu.clouddrive: DEBUG