server:
  port: 8083

spring:
  application:
    name: admin-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    # 数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接地址, useSSL=false表示禁用SSL 改用用户名和密码认证, serverTimezone时区
    url: jdbc:mysql://localhost:3306/cloud_drive?
      useSSL=false&serverTimezone=Asia/Shanghai
    # 数据库用户名
    username: root
    # 数据库密码
    password: 123456
  web:
    resources:
      static-locations: classpath:/static/, file:/D:/upload_image/
  redis:
    host: localhost   # Redis服务器地址，如果是Docker或其他环境，替换为对应IP或服务名
    port: 6379        # Redis服务器端口
    password:         # 如果有密码，在此处填写。无密码则留空或删除此行
    timeout: 5000ms   # 连接超时时间
    database: 0       # Redis数据库索引 (默认0)
    lettuce: # 使用Lettuce客户端，推荐
      pool:
        max-active: 8   # 连接池最大连接数
        max-wait: -1ms  # 连接池最大阻塞等待时间，-1表示不限制
        max-idle: 8     # 连接池最大空闲连接数
        min-idle: 0     # 连接池最小空闲连接数
    cache:
      type: redis       # 告诉Spring Cache使用Redis作为缓存存储

  mail:
    host: smtp.qq.com
    port: 465
    username: 1661391201@qq.com
    password: twvsbfzmblelcjcf
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: false
  rabbitmq:
    host: localhost # 你的 RabbitMQ 服务器地址，如果是 Docker 或远程服务器，请修改
    port: 5672      # RabbitMQ 默认端口
    username: guest # 你的 RabbitMQ 用户名
    password: guest # 你的 RabbitMQ 密码

management:
  endpoints:
    web:
      exposure:
        include: "*"
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    cn.sdu.clouddrive: DEBUG